import type { Tour } from 'nextstepjs';

const steps: Tour[] = [
  {
    tour: 'onboarding',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to Discharger',
        content: 'Let\'s take a quick tour to help you get started with creating comprehensive discharge summaries using AI and medical guidelines.',
        selector: '#patient-context-textarea',
        side: 'top',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '📝',
        title: 'Enter Patient Context',
        content: 'This is where you\'ll document the patient\'s condition, treatment, and relevant medical history. We\'ve pre-loaded some example patients to get you started.',
        selector: '#patient-context-textarea',
        side: 'top',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '📋',
        title: 'Add Documents with @',
        content: 'Type \'@\' anywhere in your notes to quickly reference and attach relevant medical documents. Try typing \'@\' now to see available documents.',
        selector: '#patient-context-textarea',
        side: 'top',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '⚡',
        title: 'Use Snippets with /',
        content: 'Type \'/\' to insert pre-written text snippets and shortcuts. This speeds up documentation with commonly used phrases and templates.',
        selector: '#patient-context-textarea',
        side: 'top',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🤖',
        title: 'Generate Discharge Summary',
        content: 'Once you\'ve entered your clinical notes, click here to generate an AI-powered discharge summary with citations from medical guidelines.',
        selector: '#generate-discharge-btn',
        side: 'top',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🔗',
        title: 'Citations & References',
        content: 'Your generated summary includes clickable citations. Click on any highlighted text to view the source medical guidelines and documentation.',
        selector: '#discharge-summary-panel',
        side: 'left',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '👁️',
        title: 'Context Viewer',
        content: 'The context viewer shows you the source documents and guidelines that informed your discharge summary. Use this to verify accuracy and understand AI reasoning.',
        selector: '#context-viewer-toggle',
        side: 'top',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '💬',
        title: 'Provide Feedback',
        content: 'If the discharge summary needs improvements, use this feedback area to guide the AI on what changes you\'d like to see.',
        selector: '#feedback-input',
        side: 'top',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
        nextRoute: '/memory',
      },
      {
        icon: '📁',
        title: 'Memory - Document Management',
        content: 'Visit the Memory page to upload and manage your medical documents, guidelines, and reference materials that the AI uses for generating summaries.',
        selector: '#memory-nav-link',
        side: 'right',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
        nextRoute: '/snippets',
        prevRoute: '/',
      },
      {
        icon: '⚡',
        title: 'Snippets - Text Templates',
        content: 'Create and manage reusable text snippets here. These shortcuts help you quickly insert commonly used phrases and templates into your clinical notes.',
        selector: '#snippets-nav-link',
        side: 'right',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
        prevRoute: '/memory',
      },
      {
        icon: '✅',
        title: 'You\'re All Set!',
        content: 'You\'re now ready to create comprehensive, citation-backed discharge summaries. Remember to upload relevant documents and create helpful snippets for the best results.',
        selector: '#sidebar',
        side: 'right',
        showControls: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
    ],
  },
];

export default steps;
